version: '3'

services:
  nodejs:
    build: requirements/nodejs/
    image: nodejs
    container_name: nodejs
    restart: always
    volumes:
      - "files_vol:/ft_transcendence"
    env_file: .env

volumes:
  files_vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: files