version: '3'

services:
  nestjs:
    build: ./requirenments/nestjs_backend
    image: nestjs
    container_name: nestjs
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./requirenments/nestjs_backend/files:/ft_transcendence
      - /ft_transcendence/node_modules
    env_file: .env
  angular:
    build: ./requirenments/angular_frontend
    image: angular
    container_name: angular
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./requirenments/angular_frontend/files:/ft_transcendence
      - /ft_transcendence/node_modules
    env_file: .env